### ISSUE TITLE
Add QR codes for links for signage

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/slides#1]

**Comment by waynegraham** [comment]
![](http://shouldiuseaqrcode.com/images/flowchart.jpg)

**Comment by nowviskie** [comment]
+1. (Also, Wayne wins GitHub for today.)

**Comment by erochest** [comment]
![robot barf](http://andylroberts.com/wp-content/uploads/2011/10/robot-barf-logo-300x267.jpg)

**Comment by jeremyboggs** [comment]
@nowviskie you mean +1? And for adding this as a feature, or for Wayne's little image?

**Comment by rondauva** [comment]
The purpose of the QR codes is to allow people to access links we put on the slideshow. We're trying to open up the type of content we can show there, and to increase engagement in our projects, link to other DH projects of interest, and to our grad fellows' projects.

Just fyi, like.

**Comment by nowviskie** [comment]
I withdraw my snark, if you think this is worth the time and effort -- that people will really use them and that they will not take up screen real estate that could be better used!  Attention to designing the slides with titles that are easily Google-able and with human-readable (not gobbledygook) custom-shortened URLs would be another option, that would also transfer over into other media and not only benefit the kind of people who would use a QR code. (Only 20% of smartphone owners have ever TRIED using a QR code, in the last survey I saw, and only 2% used them regularly. We've been seeing "QR codes are dead" posts in marketers' and tech magazines since at least 2012, and in some circles they have become kind of a joke...)
